language: node_js

node_js:
  - 8

script:
  - cd functions
  - npm install
  - npm test
  - cd ..

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $firebaseToken
  on:
    branch: master