language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
branches:
  only:
  - master
deploy:
  - provider: script
    script: bash scripts/deploy.sh dev
    on:
      branch: master