language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
script: echo "npm test disabled"
deploy:
  - provider: script
    script: bash scripts/deploy.sh dev
    on:
      branch: master