language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
script:
  - npm run bootstrap
deploy:
  skip_cleanup: true
  provider: script
  script:
    - bash scripts/deploy.sh dev
  on:
    branch: master