service: tekken-hub-api

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  role: arn:aws:iam::968177580508:role/tekken-hub-api
  stage: dev
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    COMBOS_TABLE: Combos-${opt:stage, self:provider.stage}

functions:
  tekken-hub-api:
    handler: src/index.handler
    name: tekken-hub-api-${opt:stage, self:provider.stage}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    CombosDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: submittedBy
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: submittedBy
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Combos-${opt:stage, self:provider.stage}